spring:
  application:
    name: g_75_shop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/g_75_shop
    username: postgres
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8081

logging:
  file:
    name: logs/log.log
  level:
    root: info
