spring:
  application:
    name: g_75_shop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/g_75_shop
    username: postgres
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  mail:
    username: mvorontsov713@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

server:
  port: 8081

logging:
  file:
    name: logs/log.log
  level:
    root: info
